language: node_js
node_js:
- '6'
- '7'
sudo: required
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
before_script:
- npm run build
after_success:
- npm run coveralls
deploy:
  skip_cleanup: true
  provider: npm
  email: info@molecuel.org
  api_key:
    secure: xLTtBe9NXNishEJo61ZnwUE2ZOeLS4JYfKrXIC40OhSZ2QNob9PG0kLWVIhnGTkC68a9nv93zLhUSiuppnqFiEiqz+pp5Zw39lA1KckovrgGEWtabrx6o+e2yt1iViuQbu5/YBGNfz+5LqLVlowIpRW7hXkIGrCkmrjXDT0J1bI=
  on:
    repo: molecuel/database
