language: node_js
node_js:
  - '6'
  - '7'
sudo: required
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
before_script:
  - npm run build
after_success:
  - npm run coveralls